name: wildfire 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.3
  - numpy=2.2.6
  - matplotlib=3.10.3
  - geopandas=1.0.1
  - pyomo=6.9.2
  - coin-or-cbc=2.10.12 # CBC Solver
  - glpk=5.0          # GLPK Solver
  - pip=25.1.1
  - cvxopt
  - geopy=2.4.1  
  - pyproj=3.7.1 
  - shapely=2.1.1